# Generated by Django 4.2.7 on 2023-11-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("protocol", models.CharField(max_length=10)),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=10
                    ),
                ),
            ],
        ),
    ]
